/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EventLogCollector */

#ifndef _Included_EventLogCollector
#define _Included_EventLogCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EventLogCollector
 * Method:    collectAllLogs
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_EventLogCollector_collectAllLogs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
